[build]
builder = "nixpacks"
buildCommand = "npm install react react-dom && npm install && npm run build"

[deploy]
startCommand = "npx serve dist -s -l $PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
// Thu Jan 22 16:08:04 CET 2026
